### ISSUE TITLE
status_label.ctpの共通化について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/ContentComments#11]
NetCommons/status_label.ctpは使えないでしょうか？
使えないようだと、NetCommons/status_label.ctpを汎用化しときたいです。

**Comment by akagane99** [comment]
比べてみたけど、NetCommons/status_label.ctpでもいい気がしてきました。
ContentComments/status_label.ctpのApprovingの日本語が、 ちょっとだけ違うのです。
@s-nakajima さんのご指摘でContentCommentsの日本語はこうしましたが、特にこだわりないです。

もくもく会で決めちゃいましょう。

#### Approvingの日本語

ContentComments/status_label.ctp：　未承認
NetCommons/status_label.ctp：　承認待ち

### 比較詳細

https://github.com/NetCommons3/ContentComments/blob/master/View/Elements/status_label.ctp
https://github.com/NetCommons3/ContentComments/blob/master/Locale/jpn/LC_MESSAGES/content_comments.po#L37-L38

```
msgid "Approving"
msgstr "未承認"
```

#### ContentComment::STATUS_APPROVED

https://github.com/NetCommons3/ContentComments/blob/master/Model/ContentComment.php#L33

```
const STATUS_APPROVED = '2';
```

https://github.com/NetCommons3/NetCommons/blob/master/View/Elements/status_label.ctp
https://github.com/NetCommons3/NetCommons/blob/master/Locale/jpn/LC_MESSAGES/net_commons.po#L326-L327

```
msgid "Approving"
msgstr "承認待ち"
```

#### NetCommonsBlockComponent::STATUS_APPROVED

https://github.com/NetCommons3/NetCommons/blob/master/Controller/Component/NetCommonsBlockComponent.php#L34

```
const STATUS_APPROVED = '2';
```

**Comment by akagane99** [comment]
NetCommons/status_label.ctpを使うように修正します。

**Comment by kteraguchi** [comment]
Approvingの日本語は違うままが良いそうです。
差戻しできるものとできないもので分けてるそうです。
そのまま、使うわけにはいかないですね。

デフォルトは「承認待ち」で、値が渡ってきたら上書きするような感じですかね。

**Comment by akagane99** [comment]
なるほど、賛成です。
余裕あったらpull Requestなげます。

**Comment by akagane99** [comment]
pull request こんなんでどうでしょうか？

**Comment by kteraguchi** [comment]
マージしときました。
