### ISSUE TITLE
編集権限処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/ContentComments#12]
index.ctpの編集権限処理について、下記issueにもあげたのですが、
共通化すべく、もくもく会で相談させてください。

https://github.com/NetCommons3/Blogs/issues/16

**Comment by akagane99** [comment]
アクセス権限の類は、`NetCommons.Permission`コンポーネントに共通処理としてまとまったので、
本件クローズして良さそう。
口頭確認後、クローズ予定。

**Comment by akagane99** [comment]
Current::permission('content_comment_creatable')　を使うようにする。
使っているのでクローズ
