### ISSUE TITLE
もっと見る処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/ContentComments#13]
現状全件表示になっているが、
ログインしなくてもコメント投稿できることを考慮すると、
Pagenator処理を入れといたほうが良いです。

ちなみに、ログインしなくても投稿できる件については、Bug中
https://github.com/NetCommons3/NetCommons/issues/28

**Comment by akagane99** [comment]
ページ遷移実装なら、コンテンツコメント内でのページ遷移のみ限定する必要がありそう。

~~そのためページ遷移はAjaxになりそう。~~

**Comment by akagane99** [comment]
β対応。

**Comment by akagane99** [comment]
- Pagenator処理を使ってPOSTで進める
  - Ajaxになるのであれば、その時にControllerの向き先を変える位の軽微な修正で、対応できそう。
- ページ遷移ボタンを押したら動くControllerは、動画プラグインにコメント付いてたら、動画詳細のControllerが動く。
- コンテントコメント用のページ数などのパラメータ`'contentCommnetLimit', 'contentCommnetPage'`を作って、URLパラメータに含める
  - 例 `video/view/[b_id]?contentCommnetLimit=5&contentCommnetPage=1
  - デフォルトは1ページ5件とかConstもつ。
- そのパラメータを受け取ったら、BehaviorのbeforeFind で`contentCommnetLimit=>limit, contentCommnetPage=>page` として、Pagenator処理でfindする前に渡すイメージ
  - 処理するのは、新しく作るContentCommentBehavior
  - 今あるContentCommentBehaviorは、→ContentCommentCountBehaviorに修正する

**Comment by akagane99** [comment]
@kteraguchi さん、再確認したいです。
実装中なんだけど、下記って`PaginatorHelper.php`やら、`PaginatorComponent`とか使って実現可能なんでしたっけ？
page, limitとかハックできず、また実装がよくわからず、手が止まりました。

> - コンテントコメント用のページ数などのパラメータ`'contentCommnetLimit', 'contentCommnetPage'`を作って、URLパラメータに含める

**Comment by akagane99** [comment]
@kteraguchi とりあえず、page, limitとかのまま、作業進めます。

**Comment by akagane99** [comment]
寺口さんと相談しました。
- page, limitがべた書きなので、とりあえずこのままで進む。→当issueはクローズする。
- もし問題が出るようなら、別issue立ち上げて対応する
  - 対応案としてはややこしいけど、`PaginatorHelper.php`を自作して、'contentCommnetLimit', 'contentCommnetPage'をパラメータに込めて、画面表示前に、そのパラメータをpage, limitに戻して、PaginatorComponentに渡す。
  - 実現可能かどうかは、問題発生時に再検討する
