### ISSUE TITLE
beforeFindの処理

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/ContentComments#16]
$query['fields']にContentCommentCnt.cntがあったら、JOINするようですが、
「*」があると、ContentCommentCnt.cntが2列取得されます。

結果オーライですが、afterFindで取得する処理の方が良いと思います。
そうすると、副問い合わせはなくなリますね。
https://github.com/NetCommons3/ContentComments/issues/2

**Comment by akagane99** [comment]
まだイメージできていないのですが、
afterFindで検索＋各行にcntセットする感じ、という事でしょうか？

**Comment by kteraguchi** [comment]
> afterFindで検索＋各行にcntセットする感じ、という事でしょうか？

そのイメージです。
Tagsプラグインのビヘイビアが参考になるかと思いますが、処理速度について検討の余地ありの状態です。
https://github.com/NetCommons3/Tags/issues/3

**Comment by akagane99** [comment]
~~αで対応~~

**Comment by akagane99** [comment]
参考は　https://github.com/NetCommons3/Likes
- 一覧表示にいいね数　 →　一覧表示でコンテンツコメント数
- 詳細表示でいいね数　→　詳細表示でコンテンツコメント数

のイメージ

https://github.com/NetCommons3/Tags/issues/3

> 1.リンクテーブルにタグをJOINしといてコンテンツIDをINまとめでFIND
> 2. コンテンツIDごとにリザルトに混ぜ込む

にするかどうかは、LikesのHelperとBehaviorを見ていいとこ取りをしようと思います。

**Comment by akagane99** [comment]
### コメント数を取得する - サンプル

#### x いいねプラグイン

C:\projects\NetCommons3\app\Plugin\Likes\Model\Behavior\LikeBehavior.php
1. setupで処理
2. いいねは、statusが無いので、likesテーブルにカウント項目あり。
3. コンテンツコメント数には使えない。

#### アンケートプラグイン

C:\projects\NetCommons3\app\Plugin\Questionnaires\Model\Questionnaire.php
            $val['Questionnaire']['all_answer_count'] = $this->QuestionnaireAnswerSummary->find('count', array(
1. カウント数を取得する
2. 他の処理が入っていて複雑なので、タグプラグインを参考にする

#### タグプラグイン

C:\projects\NetCommons3\app\Plugin\Tags\Model\Behavior\TagBehavior.php

``` php
/**
 * タグ情報をFind結果にまぜる
 *
 * @param Model $Model モデル
 * @param mixed $results Find結果
 * @param bool $primary primary
 * @return array $results
 * @SuppressWarnings(PHPMD.BooleanArgumentFlag)
 */
    public function afterFind(Model $Model, $results, $primary = false) {
        foreach ($results as $key => $target) {
            if (isset($target[$Model->alias]['id'])) {
                $Tag = $this->_getTagModel();
                $tags = $Tag->getTagsByContentId($Model->alias, $target[$Model->alias]['id']);
                foreach ($tags as $tag) {
                    $target['Tag'][] = $tag['Tag'];
                }
                $results[$key] = $target;
            }
        }

        return $results;
    }
```
- これを参考にいじる。
- ループ2回でいける。

![2016-01-05 11 27 41](https://cloud.githubusercontent.com/assets/2756509/12110147/71b4897a-b3cc-11e5-97fa-2167e095e0dd.jpg)
