### ISSUE TITLE
登録処理の場所

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/ContentComments#17]
現在、利用しているPlugin側のController::viewから、Postだったら登録する流れです。
https://github.com/NetCommons3/Videos/blob/bdedafe4deea2506a0345155216993b7aa568948/Controller/VideosController.php#L171

登録するaction（Formタグのaction属性）はContentCommentsControllerの方が分かりやすいと思います。
redirect先もFormに埋め込んでおけば、利用しているプラグインの画面に戻れると思います。

**Comment by akagane99** [comment]
ちょっとよくわからなかったです。
動作例を示すサンプルは何かありますか？

**Comment by kteraguchi** [comment]
Likesプラグイン（いいね）がサンプルになるかと思いましたが、
こっちはAjaxでやろうとしてるようで少し違いました。

サンプルはないですね。。。
もくもくで説明します。

**Comment by akagane99** [comment]
ContentComments　のelemet呼び出しも、修正が発生しました。

対応サンプル
https://github.com/NetCommons3/Videos/commit/a6b6b5bee6120077f7e8e7b1da6d893ff3a84200

**Comment by akagane99** [comment]
対応しました。

**Comment by akagane99** [comment]
各プラグイン側でコンテントコメントの登録処理が不要になるので、下記処理を削除した。

https://github.com/NetCommons3/Videos/commit/109026afa6e6af6d1b7a4a49766a1c4e7efb95c6
