### ISSUE TITLE
Transaction処理について

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/ContentComments#18]
他のプラグインに機能を提供するプラグインのTransaction処理について注意が必要です。

2パターンあります。
パターン１
　　提供されるプラグインの登録処理と一緒に登録されるので、
　　Transaction処理は提供されるプラグインで行う。
パターン２
　　提供するプラグイン単独で登録処理が呼ばれるので、
　　Transaction処理は提供するプラグインで行う。

他のプラグインに機能を提供するプラグイン
・Categories：パターン１
　　　Blogs,Faqs
　　
・Comments:パターン１
　　　Workflow機能があるプラグイン

・ContentComments:パターン２
　　　Blogs,Videos

・Files:未調査

・Likes:パターン２
　　　Bbses,Blogs

・Tags:パターン１
　　　Blogs

　　　　　　2015/07/01現在

今後、上記プラグインを利用する際に意識して利用しないと、Transactionがネストしてしまいます。
注意して下さい。

**Comment by kteraguchi** [comment]
上記記事を書きながら思いました。

他のプラグインに機能を提供するプラグインのTransaction処理は、
既にTransactionが始まっていなければ、自分でTransaction処理を行うロジックを共通で作っといた方が良いかもです。

**Comment by RyujiAMANO** [comment]
パターン1はafterSaveやbeforeSaveなどを利用するビヘイビアから使うこと想定ですね。

これはトランザクションいじっちゃダメですよねぇ。

パターン2は自プラグイン内のコントローラから使われるケース。
これは自前でトランザクションいじらなきゃしょうがないですもんね。

Modelにトランザクション処理入れるとコメントをつけとく意外にパターン1とパターン2を区別できないのが課題かな…

おもいきってビヘイビア用モデルと自プラグインコントローラが使うモデルを分けちゃうとかっていう手もあるのかな…

**Comment by kteraguchi** [comment]
> ビヘイビア用モデルと自プラグインコントローラが使うモデルを分けちゃうとかっていう手

ビヘイビア用モデル：トランザクションなし
自プラグインコントローラが使うモデル：トランザクションあり
利用するプラグインは使い分けてね。ということですよね。
なるほどです。

現状で問題になるとすれば、パターン1のケースを、トランザクションせずに呼び出した場合でしょうか。
まずは、注意喚起ということであげときました。

ちなみに以下情報共有です。
CakePHPのデフォルトはトランザクションのネストサポートはfalseになっています。
https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Model/Datasource/DboSource.php#L77
なので、一番最初のbegin()とcommit()のみ有効な状態です。
