### ISSUE TITLE
コンテンツコメント数の表示サンプル

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/ContentComments#2]
Videoプラグインに組み込みました。
https://github.com/NetCommons3/Videos/commit/82a602ce5f825509f6bb1751dfe0fb59a1314e1c
https://github.com/NetCommons3/Videos/commit/48d8e78736c19a2f1ec202d8ae348f9c2c8d65b3

**Comment by kteraguchi** [comment]
コンテンツコメント数の取得処理を見てみたのですが、
サブクエリーを使用しているようで、サブクエリーは使用しない方向で考えています。
ContentCommentBehavior::beforeFind

あれっ。他のプラグインでみなさん結構使ってるのかな？？
（アンケートの集計機能あたりが使わざるを得ない気がしてます。）

もくもく会で相談させてください。

コンテンツコメント数の取得については、
CakePHPだと、counterCacheという仕組みが提供されています。
http://book.cakephp.org/2.0/ja/models/associations-linking-models-together.html#countercache-count
これだと、テーブルにフィールド追加になります。

あとは、afterFindで取得して$resultsに追加してくのでも良いかと思います。

まずは、サブクエリーについて一度話しましょう。

**Comment by RyujiAMANO** [comment]
一覧でコメント数を出力することを考えるとパフォーマンス考慮してcounterCache使うことを検討するのはありですね。

その場合はコメントの追加、削除、編集、承認等の前にbelongsToアソシエーションを設定して処理おわったらアソシエーション削除する感じですかね。ちょっとややこしくなるかな。

**Comment by kteraguchi** [comment]
承認待ちも含めた件数なのか、含めない件数なのかで、数値が変わることを考慮すると、counterCacheは厳しそうです。

DebugKitで表示されるSQLログのmaybe slow次第という意見もありましたが、
Blogの記事を７件登録しただけでmaybe slowになっちゃいました。

maybe slowの判断情報載せときます。
件数（SQLログのNum. rows） / 時間（SQLログのTook (ms)） <= 20
1msecあたり、20件超えないとダメっぽいです。

https://github.com/cakephp/debug_kit/blob/2.2/View/Helper/ToolbarHelper.php#L164
https://github.com/cakephp/debug_kit/blob/2.2/View/Helper/ToolbarHelper.php#L183

どうしましょう。。。

**Comment by akagane99** [comment]
仕方ない場合、サブクエリ使う。
~~afterFindでやり方あるみたい。後で確認する。
参考：tagでafterFind やってる。~~

下記参照
https://github.com/NetCommons3/ContentComments/issues/16

**Comment by akagane99** [comment]
寺口さんに確認済み。クローズします。
