### ISSUE TITLE
承認ワークフロー共通化

### ISSUE THREAD

**Issue by kteraguchi** [NetCommons3/ContentComments#20]
https://github.com/NetCommons3/NetCommons/issues/31

**Comment by akagane99** [comment]
https://github.com/NetCommons3/Videos/issues/28

**Comment by akagane99** [comment]
ボタン対応しました。
https://github.com/NetCommons3/ContentComments/blob/28ce86afd52e90f6c8a63e3a00f4813eb80889e7/View/Elements/index.ctp#L88-L94
(リンク修正しました)

コンテンツコメントの承認は、NC2の承認のような簡易な承認なので、このままでいい気がするんだけど、
どうなんでしょうか？

**Comment by akagane99** [comment]
承認権限画面に実装漏れあり。
実装する

![default](https://cloud.githubusercontent.com/assets/2756509/12106785/56d4262c-b3a6-11e5-945b-1942ec14c767.PNG)

**Comment by akagane99** [comment]
@kteraguchi と相談済み。
コンテンツコメントの簡易承認は、現時点でこのままで行く。
下記のように、`content_comment_creatable`などコンテンツコメント専用のpermissionを時下使いしているため。

##### C:\projects\NetCommons3\app\Plugin\ContentComments\Controller\Component\ContentCommentsComponent.php

``` php
/**
 * パーミッションがあるかチェック
 *
 * @param int $process どの処理
 * @return bool true:パーミッションあり or false:パーミッションなし
 */
    private function __checkPermission($process) {
        // 登録処理 and 投稿許可あり
        if ($process == $this::PROCESS_ADD && Current::permission('content_comment_creatable')) {
            return true;

            // (編集処理 or 削除処理) and (編集許可あり or 自分で投稿したコメントなら、編集・削除可能)
        } elseif (($process == $this::PROCESS_EDIT || $process == $this::PROCESS_DELETE) && (
                Current::permission('content_comment_editable') ||
                $this->controller->data['ContentComment']['created_user'] == (int)AuthComponent::user('id')
        )) {
            return true;

            // 承認処理 and 承認許可あり
        } elseif ($process == $this::PROCESS_APPROVED && Current::permission('content_comment_publishable')) {
            return true;

        }
        return false;
    }
```

今後、簡易承認をつかいたい別のプラグインが出てきた時に、別処理に出すかどうか検討する。

本issueはクローズする。
