### ISSUE TITLE
ContentCommentビヘイビアを組み込んだらfieldsにarrayわたしてるところでwarning

### ISSUE THREAD

**Issue by RyujiAMANO** [NetCommons3/ContentComments#3]
https://github.com/NetCommons3/Blogs/blob/master/Model/BlogEntry.php#L198
みたいにfieldsにarray渡すことがあると
Warning (2): strpos() expects parameter 1 to be string, array given [APP/Plugin/ContentComments/Model/Behavior/ContentCommentBehavior.php, line 42]
ってでます。

**Comment by akagane99** [comment]
なるほど。fields、arrayもOKなのか。
修正してみます。

**Comment by akagane99** [comment]
array に対応しました。
最新で試してみてください。
