### ISSUE TITLE
サニタイズ処理

### ISSUE THREAD

**Issue by akagane99** [NetCommons3/ContentComments#43]
https://github.com/NetCommons3/NetCommons3/issues/113

https://github.com/NetCommons3/ContentComments/blob/2b63b3c42f705c8e72d322e697113a18313f80f2/View/Elements/once.ctp#L49

h()で対応

**Comment by kteraguchi** [comment]
改行されません。

```
<?php echo h(nl2br($contentComment['ContentComment']['comment'])); ?>
```

↓

```
<?php echo nl2br(h($contentComment['ContentComment']['comment'])); ?>
```

確認してほしいです。レビューがしんどいです。

**Comment by akagane99** [comment]
バグの指摘ありがとうございます。
バグは修正しますが、レビューって、コードレビューのみでなかったっけ？
それとも納品検収なのでしょうか？
ちょっとよく解からなくなりました。

↓

TELで寺口さんに確認しました。コードレビューであってました。

**Comment by akagane99** [comment]
上記developブランチでコミットしました。

**Comment by kteraguchi** [comment]
ごめんなさい。
2868ed51681e45930f9dd78e612e880c3464ae2b
で修正しちゃいました。

また、textareaは、nl2brすると、改行が<br>になってtextareaに表示されちゃいます。
d95658e74aa51cf30ca858b48138716e5c0ed5e5
で修正しました。

**Comment by akagane99** [comment]
いえいえ、がっつり対応ありがとうございました！
